package karakum.cesium

enum class Suppress {
    NESTED_CLASS_IN_EXTERNAL_INTERFACE,
    NON_EXTERNAL_DECLARATION_IN_INAPPROPRIATE_FILE,
    EXTERNAL_CLASS_CONSTRUCTOR_PROPERTY_PARAMETER,
    VAR_OVERRIDDEN_BY_VAL,
    VAR_TYPE_MISMATCH_ON_OVERRIDE,

    ;
}
