// Automatically generated - do not modify!

package react.dom

external interface AllHTMLAttributes<T> : HTMLAttributes<T> {
    // Standard HTML Attributes
    var accept: String
    var acceptCharset: String
    var action: String
    var allowFullScreen: Boolean
    var allowTransparency: Boolean
    var alt: String
    var `as`: String
    var async: Boolean
    var autoComplete: String
    var autoFocus: Boolean
    var autoPlay: Boolean
    var capture: Boolean
    var cellPadding: Number
    var cellSpacing: Number
    var charSet: String
    var challenge: String
    var checked: Boolean
    var cite: String
    var classID: String
    var cols: Number
    var colSpan: Number
    var content: String
    var controls: Boolean
    var coords: String
    var crossOrigin: String
    var data: String
    var dateTime: String
    var default: Boolean
    var defer: Boolean
    var disabled: Boolean
    var download: Any
    var encType: String
    var form: String
    var formAction: String
    var formEncType: String
    var formMethod: String
    var formNoValidate: Boolean
    var formTarget: String
    var frameBorder: Number
    var headers: String
    var height: Double
    var high: Number
    var href: String
    var hrefLang: String
    var htmlFor: String
    var httpEquiv: String
    var integrity: String
    var keyParams: String
    var keyType: String
    var kind: String
    var label: String
    var list: String
    var loop: Boolean
    var low: Number
    var manifest: String
    var marginHeight: Number
    var marginWidth: Number
    var max: Double
    var maxLength: Number
    var media: String
    var mediaGroup: String
    var method: String
    var min: Double
    var minLength: Number
    var multiple: Boolean
    var muted: Boolean
    var name: String
    var nonce: String
    var noValidate: Boolean
    var open: Boolean
    var optimum: Number
    var pattern: String
    override var placeholder: String
    var playsInline: Boolean
    var poster: String
    var preload: String
    var readOnly: Boolean
    var rel: String
    var required: Boolean
    var reversed: Boolean
    var rows: Number
    var rowSpan: Number
    var sandbox: String
    var scope: String
    var scoped: Boolean
    var scrolling: String
    var seamless: Boolean
    var selected: Boolean
    var shape: String
    var size: Number
    var sizes: String
    var span: Number
    var src: String
    var srcDoc: String
    var srcLang: String
    var srcSet: String
    var start: Number
    var step: Double
    var summary: String
    var target: String
    var type: String
    var useMap: String
    var value: String // string | ReadonlyArray<string> | number
    var width: Double
    var wmode: String
    var wrap: String
}
