// Automatically generated - do not modify!

package web.cssom

import seskar.js.JsIntValue
import seskar.js.JsVirtual
import seskar.js.JsValue

        sealed external interface LengthProperty:
        AnimationRange,
AutoLengthProperty,
Background,
BackgroundPosition,
BackgroundPositionX,
BackgroundPositionY,
BackgroundSize,
BlockSize,
BorderImageOutset,
BorderImageWidth,
Columns,
ContainIntrinsicBlockSize,
ContainIntrinsicHeight,
ContainIntrinsicInlineSize,
ContainIntrinsicSize,
ContainIntrinsicWidth,
Flex,
FlexBasis,
FontSize,
FontSmooth,
Gap,
Height,
InlineSize,
LetterSpacing,
LineHeight,
Mask,
MaskBorderOutset,
MaskBorderWidth,
MaskPosition,
MaskSize,
MaxBlockSize,
MaxHeight,
MaxInlineSize,
MaxWidth,
MinBlockSize,
MinHeight,
MinInlineSize,
MinWidth,
ObjectPosition,
Offset,
OffsetAnchor,
OffsetPosition,
OverflowClipMargin,
Perspective,
PerspectiveOrigin,
TabSize,
TextDecorationThickness,
TransformOrigin,
Translate,
VerticalAlign,
Width,
WordSpacing
